version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_interna

  nginx:
    image: nginx:latest
    container_name: servidor_web
    ports:
      - "8080:80"
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge
